name: Bug Report
description: Create a report to help us improve the Kaizen framework
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "The Kaizen agent tried to read a file outside the sandbox..."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `python -m kaizen_core.main`
        2. Add task X to backlog
        3. See error...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Kaizen or commit hash are you using?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/legendteddy/kaizen/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true